### ISSUE TITLE
Activities tab feels weird

### ISSUE THREAD

**Issue by pagenoare** [ofilipowicz/HustleGG-issues#12] opened 2019-02-17 20:07 UTC
So, I have 30 minutes available till the end of the day. And activities shows nothing, though, I think, I should be able to add any time activity but with the 30mins mark? I might be missing a point here though, but if you allow to add activity through insert event button within different duration that specificed in the task, I think that adding it from Activities would be easier and faster.

**Comment by ofilipowicz** [comment] 2019-02-17 20:56
Could it be that task list was empty OR none of tasks is planned for given day of a week?

**Comment by pagenoare** [comment] 2019-02-17 22:22
Nope. I have this task setup:
![image from ios 3](https://user-images.githubusercontent.com/1623/52920211-70ff9b80-330a-11e9-9c87-49d70fa9eae9.png)

Timeline:
![image from ios 2](https://user-images.githubusercontent.com/1623/52920224-870d5c00-330a-11e9-9b48-1755adbacb84.png)

Note that I have still 32mins available for today. I'm going to Activities tab:
![image from ios 1](https://user-images.githubusercontent.com/1623/52920231-9b515900-330a-11e9-9818-2e600f2f2f9e.png)

HOWEVER, if I go to Timeline and go with the Insert event button, I can choose and add "improve home infrastruture" just fine.
![image from ios](https://user-images.githubusercontent.com/1623/52920250-be7c0880-330a-11e9-9fdc-8de47f12c7f2.png)

**Comment by ofilipowicz** [comment] 2019-02-18 06:18
Duplicate of #5

**Closed by ofilipowicz** 2019-02-18 06:18 UTC
